wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1638748715
    t:
      1:
      - 1
      3:
      - 13
      4: 3.8.8
      5: 0.12.7
      8:
      - 5
attribute_order:
  desc: null
  value: cxywh
batch_size:
  desc: null
  value: 64
data_dir:
  desc: null
  value: null
element_order:
  desc: null
  value: raster
epochs:
  desc: null
  value: 10
exp:
  desc: null
  value: publaynet
final_iters:
  desc: null
  value: 0
log_dir:
  desc: null
  value: ./logs
lr:
  desc: null
  value: 4.5e-06
lr_decay:
  desc: null
  value: false
max_length:
  desc: null
  value: 128
n_embd:
  desc: null
  value: 512
n_head:
  desc: null
  value: 8
n_layer:
  desc: null
  value: 6
precision:
  desc: null
  value: 8
sample_every:
  desc: null
  value: 1
seed:
  desc: null
  value: 42
threshold:
  desc: null
  value: 16
train_json:
  desc: null
  value: /Users/sukays/Downloads/publaynet/train.json
val_json:
  desc: null
  value: /Users/sukays/Downloads/publaynet/val.json
warmup_iters:
  desc: null
  value: 0
